name: Stability Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Flat CLI
      uses: actions/checkout@master
      with:
        repository: FlatLang/Flat
        path: Flat

    - name: Checkout Flat JS Writer
      uses: actions/checkout@master
      with:
        repository: FlatLang/Flat-js
        path: Flat-JS

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build CLI
      run: |
        mvn -f Flat install

    - name: Build JS Writer
      run: |
        mvn -f Flat-JS install

    - name: Checkout Standard library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Standard-Library
        path: Standard-Library

    - name: Checkout Nest library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Nest
        path: Nest

    - name: Checkout Compiler-String-Extensions library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Compiler-String-Extensions
        path: Compiler-String-Extensions

    - name: Checkout Network library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Network
        path: Network

    - name: Checkout Redis library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Redis
        path: Redis

    - name: Build Stability Test
      run: |
        java -jar Flat/target/flatc.jar \
          src \
          -l Nest \
          -l Compiler-String-Extensions \
          -l Network \
          -l Redis \
          -install-dir . \
          -main stabilitytest/StabilityTest \
          -o dist/index.js \
          -target js

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: index.js
        path: dist/index.js

    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Run Stability Test
      run: |
        node dist/index.js
