name: Stability Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 4 * * *"

env:
  LOGGING_DEFAULT_SHOW_PREFIX: true
  LOGGING_DEFAULT_LOGGING_LEVEL: TRACE
  LOGGING_DEFAULT_SHOW_FORMATTING: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [node, browser]
        target: [js, es6]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 8

      - uses: actions/checkout@v3
        with:
          path: Stability-Test

      - name: Download latest Airship
        uses: FlatLang/fetch-airship@master
        with:
          includePrerelease: true

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Checkout Flat-Core library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Flat-Core
          path: Flat-Core

      - name: Build Stability Test
        working-directory: Stability-Test
        run: |
          node ../airship.js install test --target ${{ matrix.target }} --runtime ${{ matrix.runtime }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test.js
          path: Stability-Test/dist/${{ matrix.target }}/test.js

      - name: Run Stability Test
        if: ${{ matrix.runtime == 'node' }}
        working-directory: Stability-Test
        run: |
          node ../airship.js run test --target ${{ matrix.target }}

      - name: Build Browser Stability Test
        if: ${{ matrix.runtime == 'browser' }}
        working-directory: Stability-Test
        run: |
          node ../airship.js install browser --target ${{ matrix.target }}

      - name: Run Browser Stability Test
        if: ${{ matrix.runtime == 'browser' }}
        working-directory: Stability-Test
        run: |
          node dist/${{ matrix.target }}/browser-stability-test.js dist/${{ matrix.target }}/test.js
